# Pandas Complete Beginner Class — Step by Step

This notebook is designed for students who are completely new to Pandas.

We will learn in this order:

1. What Pandas is
2. Series
3. DataFrame
4. Reading CSV files
5. Understanding a dataset
6. Selecting rows and columns
7. `loc`, `iloc`, `at`, `iat`
8. Filtering
9. Sorting
10. Missing values
11. Data types and dates
12. Duplicate rows
13. Text cleaning
14. Updating values
15. Adding, renaming, and deleting columns
16. `unique()`, `nunique()`, `value_counts()`
17. `map()`, `replace()`, `apply()`
18. GroupBy and aggregation
19. Pivot tables and crosstabs
20. Concatenation
21. Merge and SQL-style joins
22. `join()` using indexes
23. Exporting data
24. Final practice questions

## 0. Before We Start — The Main Idea

Pandas mainly gives us two objects:

- **Series** → one-dimensional data, similar to one column.
- **DataFrame** → two-dimensional data, similar to an Excel table.

A DataFrame is made of multiple Series placed together.

## 1. Import Pandas

In [1]:
# Import the pandas library and give it the standard short name pd.
import pandas as pd

# Change the display setting so Pandas shows floating-point numbers with two decimal places.
pd.set_option("display.float_format", "{:.2f}".format)

# Display the installed Pandas version.
print("Pandas version:", pd.__version__)

Pandas version: 3.0.3

# Other some important set options

In [2]:
pd.set_option("display.max_rows", 100)  # Shows up to 100 rows in the output.
pd.set_option("display.max_rows", None)  # Shows all rows without limiting them.
pd.set_option("display.max_columns", 50)  # Shows up to 50 columns in the output.
pd.set_option("display.max_columns", None)  # Shows all columns.
pd.set_option("display.float_format", "{:.2f}".format)  # Displays float values with 2 decimal places.
pd.set_option("display.float_format", "{:,.2f}".format)  # Displays floats with commas and 2 decimal places, like 1,234.56.
pd.set_option("display.max_colwidth", 100)  # Shows up to 100 characters inside a column.
pd.set_option("display.max_colwidth", None)  # Shows complete text inside columns without shortening it.
pd.set_option("display.expand_frame_repr", False)  # Tries to display wide DataFrames in one line instead of wrapping.
pd.get_option("display.max_rows")  # Returns the current value of the max_rows option.
pd.describe_option("display.max_rows")  # Shows information about the max_rows option.
pd.describe_option()  # Shows information about all available Pandas options.
pd.reset_option("display.max_rows")  # Resets max_rows back to its default value.
pd.reset_option("display.float_format")  # Resets float formatting back to default.
pd.reset_option("all")  # Resets all Pandas options back to their default values.

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of rows
    could cause your rendering environment (the browser, etc.) to crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: None]
compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: False]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: <built-in method format of str object at 0x000001CEAB45E7F0>]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table, or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of
    columns could cause your rendering environment (the browser, etc.) to
    crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: None]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: None]
display.max_dir_items : int
    The number of items that will be added to `dir(...)`. 'None' value means
    unlimited. Because dir is cached, changing this option will not immediately
    affect already existing dataframes until a column is deleted or added.

    This is for instance used to suggest columns from a dataframe to tab
    completion.
    [default: 100] [currently: 100]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of rows
    could cause your rendering environment (the browser, etc.) to crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: None]
display.max_seq_items : int or None
    When pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 6]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 80]
future.distinguish_nan_and_na Whether to treat NaN entries as distinct from pd.NA in numpy-nullable and pyarrow float dtypes. By default treats both interchangeable as missing values (NaN will be coerced to NA). See discussion in https://github.com/pandas-dev/pandas/issues/32265
    [default: False] [currently: False]
future.infer_string Whether to infer sequence of str objects as pyarrow string dtype, which will be the default in pandas 3.0 (at which point this option will be deprecated).
    [default: True] [currently: True]
future.no_silent_downcasting This option is deprecated and will be removed in a future version. It has no effect.
    [default: False] [currently: False]
    (Deprecated, use `` instead.)
future.python_scalars Whether to return Python scalars instead of NumPy or PyArrow scalars. Currently experimental, setting to True is not recommended for end users.
    [default: False] [currently: False]
io.excel.ods.reader : string
    The default Excel reader engine for 'ods' files. Available options:
    auto, odf, calamine.
    [default: auto] [currently: auto]
io.excel.ods.writer : string
    The default Excel writer engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.xls.reader : string
    The default Excel reader engine for 'xls' files. Available options:
    auto, xlrd, calamine.
    [default: auto] [currently: auto]
io.excel.xlsb.reader : string
    The default Excel reader engine for 'xlsb' files. Available options:
    auto, pyxlsb, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.reader : string
    The default Excel reader engine for 'xlsm' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.writer : string
    The default Excel writer engine for 'xlsm' files. Available options:
    auto, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.reader : string
    The default Excel reader engine for 'xlsx' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsx.writer : string
    The default Excel writer engine for 'xlsx' files. Available options:
    auto, openpyxl, xlsxwriter.
    [default: auto] [currently: auto]
io.hdf.default_format : format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
    [default: None] [currently: None]
io.hdf.dropna_table : boolean
    drop ALL nan rows when appending to a table
    [default: False] [currently: False]
io.parquet.engine : string
    The default parquet reader/writer engine. Available options:
    'auto', 'pyarrow', 'fastparquet', the default is 'auto'
    [default: auto] [currently: auto]
io.sql.engine : string
    The default sql reader/writer engine. Available options:
    'auto', 'sqlalchemy', the default is 'auto'
    [default: auto] [currently: auto]
mode.chained_assignment : string
    Raise an exception, warn, or no action if trying to use chained assignment,
    The default is warn
    [default: warn] [currently: warn]
mode.copy_on_write : bool
    Use new copy-view behaviour using Copy-on-Write. No longer used,
    pandas now always uses Copy-on-Write behavior. This option will
    be removed in pandas 4.0.
    [default: True] [currently: True]
    (Deprecated, use `` instead.)
mode.performance_warnings : boolean
    Whether to show or hide PerformanceWarnings.
    [default: True] [currently: True]
mode.sim_interactive : boolean
    Whether to simulate interactive mode for purposes of testing
    [default: False] [currently: False]
mode.string_storage : string
    The default storage for StringDtype.
    [default: auto] [currently: auto]
plotting.backend : str
    The plotting backend to use. The default value is "matplotlib", the
    backend provided with pandas. Other backends can be specified by
    providing the name of the module that implements the backend.
    [default: matplotlib] [currently: matplotlib]
plotting.matplotlib.register_converters : bool or 'auto'.
    Whether to register converters with matplotlib's units registry for
    dates, times, datetimes, and Periods. Toggling to False will remove
    the converters, restoring any converters that pandas overwrote.
    [default: auto] [currently: auto]
styler.format.decimal : str
    The character representation for the decimal separator for floats and complex.
    [default: .] [currently: .]
styler.format.escape : str, optional
    Whether to escape certain characters according to the given context; html or latex.
    [default: None] [currently: None]
styler.format.formatter : str, callable, dict, optional
    A formatter object to be used as default within ``Styler.format``.
    [default: None] [currently: None]
styler.format.na_rep : str, optional
    The string representation for values identified as missing.
    [default: None] [currently: None]
styler.format.precision : int
    The precision for floats and complex numbers.
    [default: 6] [currently: 6]
styler.format.thousands : str, optional
    The character representation for thousands separator for floats, int and complex.
    [default: None] [currently: None]
styler.html.mathjax : bool
    If False will render special CSS classes to table attributes that indicate Mathjax
    will not be used in Jupyter Notebook.
    [default: True] [currently: True]
styler.latex.environment : str
    The environment to replace ``\begin{table}``. If "longtable" is used results
    in a specific longtable environment format.
    [default: None] [currently: None]
styler.latex.hrules : bool
    Whether to add horizontal rules on top and bottom and below the headers.
    [default: False] [currently: False]
styler.latex.multicol_align : {"r", "c", "l", "naive-l", "naive-r"}
    The specifier for horizontal alignment of sparsified LaTeX multicolumns. Pipe
    decorators can also be added to non-naive values to draw vertical
    rules, e.g. "\|r" will draw a rule on the left side of right aligned merged cells.
    [default: r] [currently: r]
styler.latex.multirow_align : {"c", "t", "b"}
    The specifier for vertical alignment of sparsified LaTeX multirows.
    [default: c] [currently: c]
styler.render.encoding : str
    The encoding used for output HTML and LaTeX files.
    [default: utf-8] [currently: utf-8]
styler.render.max_columns : int, optional
    The maximum number of columns that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.max_elements : int
    The maximum number of data-cell (<td>) elements that will be rendered before
    trimming will occur over columns, rows or both if needed.
    [default: 262144] [currently: 262144]
styler.render.max_rows : int, optional
    The maximum number of rows that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.repr : str
    Determine which output to use in Jupyter Notebook in {"html", "latex"}.
    [default: html] [currently: html]
styler.sparse.columns : bool
    Whether to sparsify the display of hierarchical columns. Setting to False will
    display each explicit level element in a hierarchical key for each column.
    [default: True] [currently: True]
styler.sparse.index : bool
    Whether to sparsify the display of a hierarchical index. Setting to False will
    display each explicit level element in a hierarchical key for each row.
    [default: True] [currently: True]

C:\Users\Ducat\AppData\Local\Temp\ipykernel_5028\3191784659.py:15: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option("all")  # Resets all Pandas options back to their default values.
C:\Users\Ducat\AppData\Local\Temp\ipykernel_5028\3191784659.py:15: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option("all")  # Resets all Pandas options back to their default values.

## 2. Pandas Series

A **Series** stores a one-dimensional collection of values.

Think of it like a single column in a table.

### 2.1 Create a Series from a Python List

In [3]:
# Create a normal Python list containing marks.
marks_list = [78, 85, 92, 66, 88]

# Convert the Python list into a Pandas Series.
marks = pd.Series(marks_list)

# Display the complete Series.
marks

0    78
1    85
2    92
3    66
4    88
dtype: int64

### 2.2 Create a Series with Custom Index Labels

In [4]:
# Create a Series and give each value a meaningful index label.
student_marks = pd.Series(
    [78, 85, 92, 66, 88],
    index=["Aman", "Priya", "Rohit", "Neha", "Karan"]
)

# Display the Series.
student_marks

Aman     78
Priya    85
Rohit    92
Neha     66
Karan    88
dtype: int64

### 2.3 Create a Series from a Dictionary

In [5]:
# Create a Python dictionary where keys will become indexes.
city_population = {
    "Delhi": 32,
    "Mumbai": 21,
    "Bengaluru": 14,
    "Chennai": 12
}

# Convert the dictionary into a Pandas Series.
population = pd.Series(city_population)

# Display the Series.
population

Delhi        32
Mumbai       21
Bengaluru    14
Chennai      12
dtype: int64

### 2.4 Important Series Properties

In [6]:
# Display the raw values stored inside the Series.
print("Values:", student_marks.values)
# Display the index labels of the Series.

print("Index:", student_marks.index)
# Display the data type of the Series values.
print("Data type:", student_marks.dtype)

# Display the total number of values.
print("Size:", student_marks.size)

# Display the shape of the Series.
print("Shape:", student_marks.shape)

# Display the number of dimensions.
print("Dimensions:", student_marks.ndim)

Values: [78 85 92 66 88]
Index: Index(['Aman', 'Priya', 'Rohit', 'Neha', 'Karan'], dtype='str')
Data type: int64
Size: 5
Shape: (5,)
Dimensions: 1

### 2.5 Access Values from a Series

In [117]:
# Access a value using its label.
print("Priya's marks:", student_marks.loc["Priya"])

# Access a value using its numerical position.
print("First student's marks:", student_marks.iloc[0])

# Select multiple students using labels.
print(student_marks.loc[["Aman", "Rohit", "Karan"]])

# we can go with slicing as well
print(student_marks[0:3])

Priya's marks: 85
First student's marks: 78
Aman     78
Rohit    92
Karan    88
dtype: int64
Aman     78
Priya    85
Rohit    92
dtype: int64

### 2.6 Filter a Series

In [119]:
# Create a Boolean condition that is True where marks are 80 or more.
high_marks_condition = student_marks >= 80

# Display the True/False result of the condition.
print(high_marks_condition)

# Use the Boolean condition to keep only students with marks of 80 or more.
high_scorers = student_marks[high_marks_condition]

# Display the filtered Series.
print(high_scorers)

Aman     False
Priya     True
Rohit     True
Neha     False
Karan     True
dtype: bool
Priya    85
Rohit    92
Karan    88
dtype: int64

### Student Challenge — Series

From `student_marks`, display only students whose marks are greater than 85.

**Hint:** Create a condition such as `student_marks > 85` and place it inside square brackets.

Ask students to try this before showing the solution.

In [9]:
# Write your answer here.

In [10]:
# Create a condition that checks which marks are greater than 85.
condition = student_marks > 85

# Use the condition to filter the Series.
student_marks[condition]

Rohit    92
Karan    88
dtype: int64

## 3. Pandas DataFrame

A **DataFrame** is a two-dimensional table with rows and columns.

Each column in a DataFrame is itself a Pandas Series.

### 3.1 Create a DataFrame from a Dictionary

In [11]:
# Create a dictionary where each key will become a column.
student_data = {
    "Name": ["Aman", "Priya", "Rohit", "Neha"],
    "Age": [21, 22, 23, 21],
    "City": ["Delhi", "Noida", "Ghaziabad", "Delhi"],
    "Marks": [78, 91, 85, 88]
}
# Convert the dictionary into a DataFrame.
students = pd.DataFrame(student_data)

# Display the DataFrame.
students

    Name  Age       City  Marks
0   Aman   21      Delhi     78
1  Priya   22      Noida     91
2  Rohit   23  Ghaziabad     85
3   Neha   21      Delhi     88

### 3.2 Basic DataFrame Properties

In [12]:
# Display the number of rows and columns as a tuple.
print("Shape:", students.shape)

# Display only the column names.
print("Columns:", students.columns)

# Display the row index.
print("Index:", students.index)

# Display the data type of every column.
print("Data types:")
print(students.dtypes)

# Display the total number of values in the DataFrame.
print("Total values:", students.size)

# Display the number of dimensions.
print("Dimensions:", students.ndim)

Shape: (4, 4)
Columns: Index(['Name', 'Age', 'City', 'Marks'], dtype='str')
Index: RangeIndex(start=0, stop=4, step=1)
Data types:
Name       str
Age      int64
City       str
Marks    int64
dtype: object
Total values: 16
Dimensions: 2

### 3.3 One Column vs Multiple Columns

This difference is important:

- `df["Name"]` returns a **Series**
- `df[["Name"]]` returns a **DataFrame**

In [13]:
# Select one column with single square brackets.
one_column_series = students["Name"]

# Select one column but keep the result as a DataFrame.
one_column_dataframe = students[["Name"]]

# Display the type of the first result.
print(type(one_column_series))

# Display the type of the second result.
print(type(one_column_dataframe))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

## 4. Load Our Sales CSV File

For the rest of the class we will use **`sales_data_class.csv`**.

This file intentionally contains:

- missing values,
- duplicate rows,
- mixed date formats,
- numeric columns,
- categorical columns,

so students can practise real data-cleaning work.

In [14]:
# Store the CSV file name in a variable so it is easy to reuse later.
SALES_FILE = "sales_data_class.csv"

# Read the CSV file and store the table in a DataFrame named sales.
sales = pd.read_csv(SALES_FILE)

# Display the first five rows.
sales.head()

,Name,Customer ID,Product Name,Sale Price,MRP,Rating,Sale Date,Code,Quantity,Discount %,Payment Mode
0,Alice,C001,Product1,100.0,120.0,4.5,1/8/2023,Ind-1234,1,0,UPI
1,Bob,C002,Product2,150.0,170.0,4.0,2/8/2023,Ind-1235,2,5,Card
2,Charlie,C003,NaN,200.0,NaN,3.5,3/8/2023,Ind-1236,3,10,Cash
3,David,C004,Product4,NaN,210.0,5.0,4/8/2023,Ind-1237,4,15,Net Banking
4,Eva,C005,Product5,250.0,270.0,NaN,5/8/2023,Ind-1238,1,0,UPI

## 5. First Inspection of a New Dataset

### 5.1 `head()`, `tail()`, and `sample()`

In [15]:
# Display the first five rows.
print("First five rows:")
print(sales.head())

# Display the last three rows.
print("\nLast three rows:")
print(sales.tail(3))

# Display three random rows using a fixed random_state so the same rows appear every time.
print("\nThree sample rows:")
print(sales.sample(3, random_state=42))

First five rows:
      Name Customer ID Product Name  Sale Price    MRP  Rating Sale Date  \
0    Alice        C001     Product1       100.0  120.0     4.5  1/8/2023
1      Bob        C002     Product2       150.0  170.0     4.0  2/8/2023
2  Charlie        C003          NaN       200.0    NaN     3.5  3/8/2023
3    David        C004     Product4         NaN  210.0     5.0  4/8/2023
4      Eva        C005     Product5       250.0  270.0     NaN  5/8/2023

       Code  Quantity  Discount % Payment Mode
0  Ind-1234         1           0          UPI
1  Ind-1235         2           5         Card
2  Ind-1236         3          10         Cash
3  Ind-1237         4          15  Net Banking
4  Ind-1238         1           0          UPI

Last three rows:
     Name Customer ID Product Name  Sale Price    MRP  Rating   Sale Date  \
17   Nina        C014    Product14       600.0  620.0     4.6  14-08-2023
18    Bob        C002     Product2       150.0  170.0     4.0    2/8/2023
19  Helen        C008     Product8         NaN  370.0     3.8    8/8/2023

        Code  Quantity  Discount % Payment Mode
17  Ind-1249         2           5         Card
18  Ind-1235         2           5         Card
19  Ind-1241         2           5         Card

Three sample rows:
     Name Customer ID Product Name  Sale Price    MRP  Rating   Sale Date  \
0   Alice        C001     Product1       100.0  120.0     4.5    1/8/2023
17   Nina        C014    Product14       600.0  620.0     4.6  14-08-2023
15   Nina        C014    Product14       600.0  620.0     4.6  14-08-2023

        Code  Quantity  Discount % Payment Mode
0   Ind-1234         1           0          UPI
17  Ind-1249         2           5         Card
15  Ind-1249         2           5         Card

### 5.2 Shape, Columns, and Data Types

In [16]:
# Display the number of rows and columns.
print("Shape:", sales.shape)

# Display only the number of rows.
print("Rows:", sales.shape[0])

# Display only the number of columns.
print("Columns:", sales.shape[1])

# Display all column names.
print("Column names:", sales.columns.tolist())

# Display the data type of every column.
print("\nData types:")
print(sales.dtypes)

Shape: (20, 11)
Rows: 20
Columns: 11
Column names: ['Name', 'Customer ID', 'Product Name', 'Sale Price', 'MRP', 'Rating', 'Sale Date', 'Code', 'Quantity', 'Discount %', 'Payment Mode']

Data types:
Name                str
Customer ID         str
Product Name        str
Sale Price      float64
MRP             float64
Rating          float64
Sale Date           str
Code                str
Quantity          int64
Discount %        int64
Payment Mode        str
dtype: object

### 5.3 `info()`

In [17]:
# Show a compact summary containing row count, non-null values, and data types.
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          20 non-null     str
 1   Customer ID   20 non-null     str
 2   Product Name  16 non-null     str
 3   Sale Price    16 non-null     float64
 4   MRP           16 non-null     float64
 5   Rating        17 non-null     float64
 6   Sale Date     17 non-null     str
 7   Code          20 non-null     str
 8   Quantity      20 non-null     int64
 9   Discount %    20 non-null     int64
 10  Payment Mode  20 non-null     str
dtypes: float64(3), int64(2), str(6)
memory usage: 2.5 KB

### 5.4 `describe()`

In [18]:
# Calculate summary statistics for numeric columns.
numeric_summary = sales.describe()

# Display the numeric summary.
numeric_summary

       Sale Price         MRP     Rating  Quantity  Discount %
count   16.000000   16.000000  17.000000  20.00000   20.000000
mean   371.875000  385.000000   4.294118   2.15000    5.750000
std    197.457801  196.977156   0.424957   1.03999    5.199949
min    100.000000  120.000000   3.500000   1.00000    0.000000
25%    187.500000  200.000000   4.000000   1.00000    0.000000
50%    375.000000  370.000000   4.300000   2.00000    5.000000
75%    562.500000  582.500000   4.600000   3.00000   10.000000
max    650.000000  670.000000   5.000000   4.00000   15.000000

In [19]:
# Transpose the summary so statistics become columns and original columns become rows.
sales.describe().T

            count        mean         std    min    25%    50%    75%    max
Sale Price   16.0  371.875000  197.457801  100.0  187.5  375.0  562.5  650.0
MRP          16.0  385.000000  196.977156  120.0  200.0  370.0  582.5  670.0
Rating       17.0    4.294118    0.424957    3.5    4.0    4.3    4.6    5.0
Quantity     20.0    2.150000    1.039990    1.0    1.0    2.0    3.0    4.0
Discount %   20.0    5.750000    5.199949    0.0    0.0    5.0   10.0   15.0

### 🎯 Student Challenge — Understand the Dataset

Without manually counting, print the total number of rows and the total number of columns in `sales`.

**Hint:** Use `sales.shape`.

Ask students to try this before showing the solution.

In [20]:
# Write your answer here.

**Teacher solution — run this only after students have tried.**

In [21]:
# Print the first value from shape to get the row count.
print("Total rows:", sales.shape[0])

# Print the second value from shape to get the column count.
print("Total columns:", sales.shape[1])

Total rows: 20
Total columns: 11

## 6. Selecting Columns and Rows

### 6.1 Select One Column

In [22]:
# Select the Name column as a Series.
names = sales["Name"]

# Display the first five values.
names.head()

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: str

### 6.2 Select Multiple Columns

In [23]:
# Select Name, Product Name, and Sale Price as a new DataFrame.
basic_sales = sales[["Name", "Product Name", "Sale Price"]]

# Display the first five rows.
basic_sales.head()

      Name Product Name  Sale Price
0    Alice     Product1       100.0
1      Bob     Product2       150.0
2  Charlie          NaN       200.0
3    David     Product4         NaN
4      Eva     Product5       250.0

### 6.3 Basic Row Slicing

In [24]:
# Select rows from position 0 up to, but not including, position 5.
first_five_rows = sales[0:5]

# Display the selected rows.
first_five_rows

,Name,Customer ID,Product Name,Sale Price,MRP,Rating,Sale Date,Code,Quantity,Discount %,Payment Mode
0,Alice,C001,Product1,100.0,120.0,4.5,1/8/2023,Ind-1234,1,0,UPI
1,Bob,C002,Product2,150.0,170.0,4.0,2/8/2023,Ind-1235,2,5,Card
2,Charlie,C003,NaN,200.0,NaN,3.5,3/8/2023,Ind-1236,3,10,Cash
3,David,C004,Product4,NaN,210.0,5.0,4/8/2023,Ind-1237,4,15,Net Banking
4,Eva,C005,Product5,250.0,270.0,NaN,5/8/2023,Ind-1238,1,0,UPI

In [25]:
# Select every second row from the first ten rows.
alternate_rows = sales[0:10:2]

# Display the selected rows.
alternate_rows

,Name,Customer ID,Product Name,Sale Price,MRP,Rating,Sale Date,Code,Quantity,Discount %,Payment Mode
0,Alice,C001,Product1,100.0,120.0,4.5,1/8/2023,Ind-1234,1,0,UPI
2,Charlie,C003,NaN,200.0,NaN,3.5,3/8/2023,Ind-1236,3,10,Cash
4,Eva,C005,Product5,250.0,270.0,NaN,5/8/2023,Ind-1238,1,0,UPI
6,Grace,C007,Product7,350.0,NaN,4.1,7/8/2023,Ind-1240,1,0,UPI
8,Ivy,C009,Product9,400.0,420.0,NaN,NaN,Ind-1242,3,10,Cash

## 7. `loc`, `iloc`, `at`, and `iat`

- `loc` → label-based selection
- `iloc` → position-based selection
- `at` → one cell using row/column labels
- `iat` → one cell using numerical positions

### 7.1 `loc`

In [26]:
# Select rows with labels 0 through 4 and the columns from Name through MRP.
loc_example = sales.loc[0:4, "Name":"MRP"]

# Display the result.
loc_example

      Name Customer ID Product Name  Sale Price    MRP
0    Alice        C001     Product1       100.0  120.0
1      Bob        C002     Product2       150.0  170.0
2  Charlie        C003          NaN       200.0    NaN
3    David        C004     Product4         NaN  210.0
4      Eva        C005     Product5       250.0  270.0

### 7.2 `iloc`

In [27]:
# Select the first five rows and the first four columns using numerical positions.
iloc_example = sales.iloc[0:5, 0:4]

# Display the result.
iloc_example

      Name Customer ID Product Name  Sale Price
0    Alice        C001     Product1       100.0
1      Bob        C002     Product2       150.0
2  Charlie        C003          NaN       200.0
3    David        C004     Product4         NaN
4      Eva        C005     Product5       250.0

### 7.3 `at` and `iat`

In [28]:
# Read one cell using a row label and column label.
print("Using at:", sales.at[0, "Name"])

# Read one cell using a row position and column position.
print("Using iat:", sales.iat[0, 0])

Using at: Alice
Using iat: Alice

### 🎯 Student Challenge — `loc` and `iloc`

Display rows 2 to 6 for the columns `Name`, `Sale Price`, and `Rating` using `loc`. Then display the same rows using `iloc`.

**Hint:** Remember that `loc` label slicing includes the ending label, while `iloc` position slicing excludes the ending position.

Ask students to try this before showing the solution.

In [29]:
# Write your answer here.

**Teacher solution — run this only after students have tried.**

In [30]:
# Use loc with row labels 2 through 6 and explicit column names.
print(sales.loc[2:6, ["Name", "Sale Price", "Rating"]])

# Use iloc with row positions 2 through 6 and the positions of Name, Sale Price, and Rating.
print(sales.iloc[2:7, [0, 3, 5]])

      Name  Sale Price  Rating
2  Charlie       200.0     3.5
3    David         NaN     5.0
4      Eva       250.0     NaN
5    Frank       300.0     4.7
6    Grace       350.0     4.1
      Name  Sale Price  Rating
2  Charlie       200.0     3.5
3    David         NaN     5.0
4      Eva       250.0     NaN
5    Frank       300.0     4.7
6    Grace       350.0     4.1

## 8. Filtering Data

### 8.1 One Condition

In [31]:
# Create a condition that checks whether Rating is 4.5 or higher.
rating_condition = sales["Rating"] >= 4.5

# Use the condition to keep only matching rows.
high_rated_sales = sales[rating_condition]

# Display selected columns from the filtered data.
high_rated_sales[["Name", "Product Name", "Rating"]]

     Name Product Name  Rating
0   Alice     Product1     4.5
3   David     Product4     5.0
5   Frank          NaN     4.7
10   Kara    Product11     4.9
13   Nina    Product14     4.6
15   Nina    Product14     4.6
16  Alice     Product1     4.5
17   Nina    Product14     4.6

### 8.2 Multiple Conditions with `&`

In [32]:
# Create the first condition for ratings of at least 4.
condition_one = sales["Rating"] >= 4.0

# Create the second condition for sale prices above 200.
condition_two = sales["Sale Price"] > 200

# Combine both conditions using the AND operator &.
filtered_sales = sales[condition_one & condition_two]

# Display the filtered rows.
filtered_sales[["Name", "Sale Price", "Rating"]]

     Name  Sale Price  Rating
5   Frank       300.0     4.7
6   Grace       350.0     4.1
9    Jack       450.0     4.3
10   Kara       500.0     4.9
13   Nina       600.0     4.6
14  Oscar       650.0     4.2
15   Nina       600.0     4.6
17   Nina       600.0     4.6

### 8.3 OR Condition with `|`

In [33]:
# Create a condition for cash payments.
cash_condition = sales["Payment Mode"] == "Cash"

# Create another condition for UPI payments.
upi_condition = sales["Payment Mode"] == "UPI"

# Keep rows where either condition is True.
cash_or_upi = sales[cash_condition | upi_condition]

# Display a few useful columns.
cash_or_upi[["Name", "Payment Mode", "Sale Price"]]

       Name Payment Mode  Sale Price
0     Alice          UPI       100.0
2   Charlie         Cash       200.0
4       Eva          UPI       250.0
6     Grace          UPI       350.0
8       Ivy         Cash       400.0
10     Kara          UPI       500.0
12     Mona         Cash       550.0
14    Oscar          UPI       650.0
16    Alice          UPI       100.0

### 8.4 `isin()`

In [34]:
# Create a list of payment methods we want to keep.
wanted_methods = ["UPI", "Card"]

# Check whether each Payment Mode exists in the list.
method_condition = sales["Payment Mode"].isin(wanted_methods)

# Filter the DataFrame using the condition.
sales[method_condition][["Name", "Payment Mode"]]

     Name Payment Mode
0   Alice          UPI
1     Bob         Card
4     Eva          UPI
5   Frank         Card
6   Grace          UPI
7   Helen         Card
10   Kara          UPI
11    Leo         Card
14  Oscar          UPI
15   Nina         Card
16  Alice          UPI
17   Nina         Card
18    Bob         Card
19  Helen         Card

### 8.5 `between()`

In [35]:
# Check which Sale Price values are between 200 and 500, including both limits.
price_condition = sales["Sale Price"].between(200, 500)

# Display matching rows.
sales[price_condition][["Name", "Sale Price"]]

       Name  Sale Price
2   Charlie       200.0
4       Eva       250.0
5     Frank       300.0
6     Grace       350.0
8       Ivy       400.0
9      Jack       450.0
10     Kara       500.0

### 🎯 Student Challenge — Filtering

Find rows where `Rating` is at least 4.0 **and** `Quantity` is greater than 2. Show only `Name`, `Rating`, and `Quantity`.

**Hint:** Use parentheses around each condition and combine them using `&`.

Ask students to try this before showing the solution.

In [36]:
# Write your answer here.

**Teacher solution — run this only after students have tried.**

In [37]:
# Create the rating condition.
rating_ok = sales["Rating"] >= 4.0

# Create the quantity condition.
quantity_ok = sales["Quantity"] > 2

# Apply both conditions and select only the requested columns.
sales.loc[rating_ok & quantity_ok, ["Name", "Rating", "Quantity"]]

     Name  Rating  Quantity
3   David     5.0         4
9    Jack     4.3         4
13   Nina     4.6         4

## 9. Sorting Data

### 9.1 Sort One Column

In [38]:
# Sort rows by Sale Price from lowest to highest.
price_low_to_high = sales.sort_values("Sale Price", ascending=True)

# Display the first ten rows after sorting.
price_low_to_high[["Name", "Sale Price"]].head(10)

       Name  Sale Price
0     Alice       100.0
16    Alice       100.0
1       Bob       150.0
18      Bob       150.0
2   Charlie       200.0
4       Eva       250.0
5     Frank       300.0
6     Grace       350.0
8       Ivy       400.0
9      Jack       450.0

### 9.2 Sort by Multiple Columns

In [39]:
# Sort first by Payment Mode and then by Rating from highest to lowest.
multi_sort = sales.sort_values(
    by=["Payment Mode", "Rating"],
    ascending=[True, False]
)

# Display selected columns.
multi_sort[["Name", "Payment Mode", "Rating"]].head(10)

       Name Payment Mode  Rating
5     Frank         Card     4.7
15     Nina         Card     4.6
17     Nina         Card     4.6
1       Bob         Card     4.0
18      Bob         Card     4.0
7     Helen         Card     3.8
19    Helen         Card     3.8
11      Leo         Card     NaN
12     Mona         Cash     3.9
2   Charlie         Cash     3.5

### 9.3 Largest and Smallest Values

In [40]:
# Find the three rows with the largest Sale Price values.
top_three_sales = sales.nlargest(3, "Sale Price")

# Display the result.
top_three_sales[["Name", "Sale Price"]]

     Name  Sale Price
14  Oscar       650.0
13   Nina       600.0
15   Nina       600.0

In [41]:
# Find the three rows with the smallest non-missing MRP values.
lowest_three_mrp = sales.nsmallest(3, "MRP")

# Display the result.
lowest_three_mrp[["Name", "MRP"]]

     Name    MRP
0   Alice  120.0
16  Alice  120.0
1     Bob  170.0

## 10. Missing Values

Missing values usually appear as `NaN`.

Before filling or deleting them, first **measure** the problem.

### 10.1 Find Missing Values

In [42]:
# Return True where a value is missing and False where a value exists.
missing_matrix = sales.isna()

# Display the first five rows of the True/False result.
missing_matrix.head()

,Name,Customer ID,Product Name,Sale Price,MRP,Rating,Sale Date,Code,Quantity,Discount %,Payment Mode
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,True,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,False

In [43]:
# Count missing values in every column.
missing_per_column = sales.isna().sum()

# Display the count.
missing_per_column

Name            0
Customer ID     0
Product Name    4
Sale Price      4
MRP             4
Rating          3
Sale Date       3
Code            0
Quantity        0
Discount %      0
Payment Mode    0
dtype: int64

In [44]:
# Count all missing values in the complete DataFrame.
total_missing = sales.isna().sum().sum()

# Display the total.
print("Total missing values:", total_missing)

Total missing values: 18

### 10.2 Check Missing Values in One Column

In [45]:
# Check which values are missing only in the MRP column.
mrp_missing = sales["MRP"].isna()

# Count how many MRP values are missing.
print("Missing MRP values:", mrp_missing.sum())

Missing MRP values: 4

### 10.3 `dropna()` — Remove Rows or Columns

In [46]:
# Create a fresh copy so the original sales DataFrame is not changed.
drop_demo = sales.copy()

# Remove rows that contain at least one missing value and return a new DataFrame.
rows_without_missing = drop_demo.dropna(axis=0)

# Display the shape before and after removing rows.
print("Before:", drop_demo.shape)
print("After removing rows:", rows_without_missing.shape)

Before: (20, 11)
After removing rows: (8, 11)

In [47]:
# Remove columns that contain at least one missing value and return a new DataFrame.
columns_without_missing = drop_demo.dropna(axis=1)

# Display the remaining column names.
print(columns_without_missing.columns.tolist())

['Name', 'Customer ID', 'Code', 'Quantity', 'Discount %', 'Payment Mode']

### 10.4 Fill Missing Values with a Fixed Value

In [48]:
# Create a fresh copy for the fill demonstration.
fill_demo = sales.copy()

# Fill missing Product Name values with a clear text label.
fill_demo["Product Name"] = fill_demo["Product Name"].fillna("Unknown Product")

# Display the first ten Product Name values.
fill_demo["Product Name"].head(10)

0           Product1
1           Product2
2    Unknown Product
3           Product4
4           Product5
5    Unknown Product
6           Product7
7           Product8
8           Product9
9    Unknown Product
Name: Product Name, dtype: str

### 10.5 Fill Numeric Missing Values with Mean, Median, and Mode

In [49]:
# Create a fresh copy for numeric filling.
numeric_fill_demo = sales.copy()

# Calculate the mean of Sale Price while automatically ignoring missing values.
sale_price_mean = numeric_fill_demo["Sale Price"].mean()

# Fill missing Sale Price values using the mean.
numeric_fill_demo["Sale Price"] = numeric_fill_demo["Sale Price"].fillna(sale_price_mean)

# Display the calculated mean and the remaining missing count.
print("Mean Sale Price:", sale_price_mean)
print("Missing Sale Price after fill:", numeric_fill_demo["Sale Price"].isna().sum())

Mean Sale Price: 371.875
Missing Sale Price after fill: 0

In [50]:
# Create another fresh copy for the median example.
median_fill_demo = sales.copy()

# Calculate the median MRP.
mrp_median = median_fill_demo["MRP"].median()

# Fill missing MRP values with the median.
median_fill_demo["MRP"] = median_fill_demo["MRP"].fillna(mrp_median)

# Display the median and remaining missing count.
print("Median MRP:", mrp_median)
print("Missing MRP after fill:", median_fill_demo["MRP"].isna().sum())

Median MRP: 370.0
Missing MRP after fill: 0

In [51]:
# Create another fresh copy for the mode example.
mode_fill_demo = sales.copy()

# Get the most common Rating and take the first mode value.
rating_mode = mode_fill_demo["Rating"].mode()[0]

# Fill missing Rating values with the mode.
mode_fill_demo["Rating"] = mode_fill_demo["Rating"].fillna(rating_mode)

# Display the mode.
print("Mode Rating:", rating_mode)

Mode Rating: 4.6

> **Teaching point:** Do not automatically use mean for every numeric column.  
> The correct treatment depends on what the column represents and why the value is missing.

### 🎯 Student Challenge — Missing Values

How many missing values are present in `Sale Date`? Then create a new DataFrame in which missing `Product Name` values are filled with `Not Available`.

**Hint:** Use `isna().sum()` for the first part and `fillna()` for the second.

Ask students to try this before showing the solution.

In [52]:
# Write your answer here.

**Teacher solution — run this only after students have tried.**

In [53]:
# Count missing values in Sale Date.
print("Missing Sale Date values:", sales["Sale Date"].isna().sum())

# Create a copy so the original data remains unchanged.
question_fill = sales.copy()

# Fill missing Product Name values.
question_fill["Product Name"] = question_fill["Product Name"].fillna("Not Available")

# Display the first ten rows.
question_fill.head(10)

Missing Sale Date values: 3

,Name,Customer ID,Product Name,Sale Price,MRP,Rating,Sale Date,Code,Quantity,Discount %,Payment Mode
0,Alice,C001,Product1,100.0,120.0,4.5,1/8/2023,Ind-1234,1,0,UPI
1,Bob,C002,Product2,150.0,170.0,4.0,2/8/2023,Ind-1235,2,5,Card
2,Charlie,C003,Not Available,200.0,NaN,3.5,3/8/2023,Ind-1236,3,10,Cash
3,David,C004,Product4,NaN,210.0,5.0,4/8/2023,Ind-1237,4,15,Net Banking
4,Eva,C005,Product5,250.0,270.0,NaN,5/8/2023,Ind-1238,1,0,UPI
5,Frank,C006,Not Available,300.0,320.0,4.7,NaN,Ind-1239,2,5,Card
6,Grace,C007,Product7,350.0,NaN,4.1,7/8/2023,Ind-1240,1,0,UPI
7,Helen,C008,Product8,NaN,370.0,3.8,8/8/2023,Ind-1241,2,5,Card
8,Ivy,C009,Product9,400.0,420.0,NaN,NaN,Ind-1242,3,10,Cash
9,Jack,C010,Not Available,450.0,NaN,4.3,10/8/2023,Ind-1243,4,15,Net Banking

## 11. Data Types and Date Conversion

### 11.1 Convert a Column with `astype()`

In [54]:
# Create a copy for data-type experiments.
type_demo = sales.copy()

# Convert Quantity from integer to float for demonstration.
type_demo["Quantity"] = type_demo["Quantity"].astype(float)

# Display the new data type.
print(type_demo["Quantity"].dtype)

float64

### 11.2 Convert Mixed Date Text to Real Datetime

In [55]:
# Create a copy so the original Sale Date text remains available for comparison.
date_demo = sales.copy()

# Convert Sale Date into Pandas datetime while treating day as the first date component.
date_demo["Sale Date"] = pd.to_datetime(
    date_demo["Sale Date"],
    dayfirst=True,
    errors="coerce"
)

# Display the converted date column and its data type.
print(date_demo[["Sale Date"]].head(15))
print(date_demo["Sale Date"].dtype)

    Sale Date
0  2023-08-01
1  2023-08-02
2  2023-08-03
3  2023-08-04
4  2023-08-05
5         NaT
6  2023-08-07
7  2023-08-08
8         NaT
9  2023-08-10
10 2023-08-11
11        NaT
12        NaT
13        NaT
14        NaT
datetime64[us]

`errors="coerce"` means values that cannot be converted become `NaT` instead of stopping the program with an error.

`NaT` means **Not a Time**, which is the datetime version of a missing value.

### 11.3 Extract Date Parts

In [56]:
# Extract the year from the datetime column.
date_demo["Year"] = date_demo["Sale Date"].dt.year

# Extract the month number.
date_demo["Month"] = date_demo["Sale Date"].dt.month

# Extract the day of the month.
date_demo["Day"] = date_demo["Sale Date"].dt.day

# Extract the weekday name.
date_demo["Day Name"] = date_demo["Sale Date"].dt.day_name()

# Display the new date-related columns.
date_demo[["Sale Date", "Year", "Month", "Day", "Day Name"]].head(10)

   Sale Date    Year  Month   Day   Day Name
0 2023-08-01  2023.0    8.0   1.0    Tuesday
1 2023-08-02  2023.0    8.0   2.0  Wednesday
2 2023-08-03  2023.0    8.0   3.0   Thursday
3 2023-08-04  2023.0    8.0   4.0     Friday
4 2023-08-05  2023.0    8.0   5.0   Saturday
5        NaT     NaN    NaN   NaN        NaN
6 2023-08-07  2023.0    8.0   7.0     Monday
7 2023-08-08  2023.0    8.0   8.0    Tuesday
8        NaT     NaN    NaN   NaN        NaN
9 2023-08-10  2023.0    8.0  10.0   Thursday

## 12. Duplicate Rows

### 12.1 Find Duplicate Rows

In [57]:
# Check every row and return True for repeated rows after their first occurrence.
duplicate_flags = sales.duplicated()

# Display the Boolean result.
print(duplicate_flags)

# Count the total number of duplicated rows.
print("Duplicate rows:", duplicate_flags.sum())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18     True
19     True
dtype: bool
Duplicate rows: 3

### 12.2 Display All Duplicate Records

In [58]:
# Keep every row that belongs to a duplicated group, including the first occurrence.
all_duplicate_records = sales[sales.duplicated(keep=False)]

# Display the duplicate records.
all_duplicate_records

,Name,Customer ID,Product Name,Sale Price,MRP,Rating,Sale Date,Code,Quantity,Discount %,Payment Mode
1,Bob,C002,Product2,150.0,170.0,4.0,2/8/2023,Ind-1235,2,5,Card
7,Helen,C008,Product8,NaN,370.0,3.8,8/8/2023,Ind-1241,2,5,Card
15,Nina,C014,Product14,600.0,620.0,4.6,14-08-2023,Ind-1249,2,5,Card
17,Nina,C014,Product14,600.0,620.0,4.6,14-08-2023,Ind-1249,2,5,Card
18,Bob,C002,Product2,150.0,170.0,4.0,2/8/2023,Ind-1235,2,5,Card
19,Helen,C008,Product8,NaN,370.0,3.8,8/8/2023,Ind-1241,2,5,Card

### 12.3 Find Duplicates Based on Selected Columns

In [59]:
# Check duplicate order codes only instead of comparing every column.
duplicate_codes = sales.duplicated(subset=["Code"], keep=False)

# Display rows whose Code appears more than once.
sales.loc[duplicate_codes, ["Code", "Name", "Product Name", "Sale Price"]]

        Code   Name Product Name  Sale Price
1   Ind-1235    Bob     Product2       150.0
7   Ind-1241  Helen     Product8         NaN
15  Ind-1249   Nina    Product14       600.0
17  Ind-1249   Nina    Product14       600.0
18  Ind-1235    Bob     Product2       150.0
19  Ind-1241  Helen     Product8         NaN

### 12.4 Remove Duplicate Rows

In [60]:
# Create a copy so the original sales DataFrame still contains duplicates for teaching.
dedup_sales = sales.copy()

# Remove exact duplicate rows and reset the row index.
dedup_sales = dedup_sales.drop_duplicates().reset_index(drop=True)

# Compare the number of rows before and after duplicate removal.
print("Rows before:", len(sales))
print("Rows after:", len(dedup_sales))

Rows before: 20
Rows after: 17

### 🎯 Student Challenge — Duplicates

Count duplicate rows using only the combination of `Name` and `Product Name`.

**Hint:** Use the `subset=` parameter inside `duplicated()`.

Ask students to try this before showing the solution.

In [61]:
# Write your answer here.

**Teacher solution — run this only after students have tried.**

In [62]:
# Check duplicates based only on Name and Product Name.
name_product_duplicates = sales.duplicated(
    subset=["Name", "Product Name"]
)

# Count how many repeated combinations exist.
print(name_product_duplicates.sum())

5

## 13. Text Cleaning with `.str`

String methods are useful when text contains extra spaces, inconsistent case, or unwanted characters.

We will use a small example first so we do not unnecessarily damage the original names.

In [63]:
# Create a small Series containing deliberately messy text.
messy_names = pd.Series(["  alice", "BOB  ", "  cHaRlIe  "])

# Remove spaces from the beginning and end of every value.
clean_names = messy_names.str.strip()

# Convert each name to title case.
clean_names = clean_names.str.title()

# Display the original and cleaned values together.
pd.DataFrame({"Original": messy_names, "Cleaned": clean_names})

      Original  Cleaned
0        alice    Alice
1        BOB        Bob
2    cHaRlIe    Charlie

### 13.1 Search Text with `str.contains()`

In [64]:
# Check whether Product Name contains the text Product1.
contains_product1 = sales["Product Name"].str.contains(
    "Product1",
    case=False,
    na=False
)

# Display matching rows.
sales.loc[contains_product1, ["Name", "Product Name"]]

     Name Product Name
0   Alice     Product1
10   Kara    Product11
11    Leo    Product12
12   Mona    Product13
13   Nina    Product14
15   Nina    Product14
16  Alice     Product1
17   Nina    Product14

## 14. Updating Values

### 14.1 Update One Cell with `at`

In [65]:
# Create a copy so changes do not affect the original data.
update_demo = sales.copy()

# Change one Product Name value using a row label and column label.
update_demo.at[0, "Product Name"] = "Updated Product"

# Display the first two rows.
update_demo.head(2)

,Name,Customer ID,Product Name,Sale Price,MRP,Rating,Sale Date,Code,Quantity,Discount %,Payment Mode
0,Alice,C001,Updated Product,100.0,120.0,4.5,1/8/2023,Ind-1234,1,0,UPI
1,Bob,C002,Product2,150.0,170.0,4.0,2/8/2023,Ind-1235,2,5,Card

### 14.2 Conditional Update with `loc`

In [66]:
# Create another copy for conditional updating.
conditional_demo = sales.copy()

# Create a condition for ratings below 4.
low_rating = conditional_demo["Rating"] < 4

# Update only the matching Rating values to 4 for demonstration.
conditional_demo.loc[low_rating, "Rating"] = 4

# Display selected columns.
conditional_demo[["Name", "Rating"]].head(10)

      Name  Rating
0    Alice     4.5
1      Bob     4.0
2  Charlie     4.0
3    David     5.0
4      Eva     NaN
5    Frank     4.7
6    Grace     4.1
7    Helen     4.0
8      Ivy     NaN
9     Jack     4.3

### 14.3 Replace Values

In [67]:
# Create a copy for replace demonstration.
replace_demo = sales.copy()

# Replace UPI with Unified Payments Interface and Card with Credit/Debit Card.
replace_demo["Payment Mode"] = replace_demo["Payment Mode"].replace(
    {
        "UPI": "Unified Payments Interface",
        "Card": "Credit/Debit Card"
    }
)

# Display the unique values after replacement.
replace_demo["Payment Mode"].unique()

<ArrowStringArray>
['Unified Payments Interface', 'Credit/Debit Card', 'Cash', 'Net Banking']
Length: 4, dtype: str

## 15. Add, Rename, and Delete Columns

### 15.1 Add Calculated Columns

In [68]:
# Start from data with exact duplicate rows removed.
analysis_sales = sales.drop_duplicates().copy()

# Fill missing Sale Price values with the median so calculations can continue.
analysis_sales["Sale Price"] = analysis_sales["Sale Price"].fillna(
    analysis_sales["Sale Price"].median()
)

# Calculate gross sales before discount.
analysis_sales["Gross Sales"] = (
    analysis_sales["Sale Price"] * analysis_sales["Quantity"]
)

# Calculate the discount amount.
analysis_sales["Discount Amount"] = (
    analysis_sales["Gross Sales"] * analysis_sales["Discount %"] / 100
)

# Calculate net sales after discount.
analysis_sales["Net Sales"] = (
    analysis_sales["Gross Sales"] - analysis_sales["Discount Amount"]
)

# Display the calculated columns.
analysis_sales[
    [
        "Name",
        "Sale Price",
        "Quantity",
        "Discount %",
        "Gross Sales",
        "Discount Amount",
        "Net Sales",
    ]
].head()

,Name,Sale Price,Quantity,Discount %,Gross Sales,Discount Amount,Net Sales
0,Alice,100.0,1,0,100.0,0.0,100.0
1,Bob,150.0,2,5,300.0,15.0,285.0
2,Charlie,200.0,3,10,600.0,60.0,540.0
3,David,375.0,4,15,1500.0,225.0,1275.0
4,Eva,250.0,1,0,250.0,0.0,250.0

### 15.2 Rename a Column

In [69]:
# Create a copy so the main analysis DataFrame keeps its original column names.
rename_demo = analysis_sales.copy()

# Rename Sale Price to Selling Price.
rename_demo = rename_demo.rename(
    columns={"Sale Price": "Selling Price"}
)

# Display the new column names.
print(rename_demo.columns.tolist())

['Name', 'Customer ID', 'Product Name', 'Selling Price', 'MRP', 'Rating', 'Sale Date', 'Code', 'Quantity', 'Discount %', 'Payment Mode', 'Gross Sales', 'Discount Amount', 'Net Sales']

### 15.3 Drop a Column

In [70]:
# Create a copy for the drop demonstration.
drop_column_demo = analysis_sales.copy()

# Remove the Discount Amount column.
drop_column_demo = drop_column_demo.drop(
    columns=["Discount Amount"]
)

# Display the remaining column names.
print(drop_column_demo.columns.tolist())

['Name', 'Customer ID', 'Product Name', 'Sale Price', 'MRP', 'Rating', 'Sale Date', 'Code', 'Quantity', 'Discount %', 'Payment Mode', 'Gross Sales', 'Net Sales']

### 15.4 Insert a Column at a Specific Position

In [71]:
# Create a copy for insert demonstration.
insert_demo = analysis_sales.copy()

# Insert a new column at position 2.
insert_demo.insert(
    2,
    "Country",
    "India"
)

# Display the first few rows.
insert_demo.head()

,Name,Customer ID,Country,Product Name,Sale Price,MRP,Rating,Sale Date,Code,Quantity,Discount %,Payment Mode,Gross Sales,Discount Amount,Net Sales
0,Alice,C001,India,Product1,100.0,120.0,4.5,1/8/2023,Ind-1234,1,0,UPI,100.0,0.0,100.0
1,Bob,C002,India,Product2,150.0,170.0,4.0,2/8/2023,Ind-1235,2,5,Card,300.0,15.0,285.0
2,Charlie,C003,India,NaN,200.0,NaN,3.5,3/8/2023,Ind-1236,3,10,Cash,600.0,60.0,540.0
3,David,C004,India,Product4,375.0,210.0,5.0,4/8/2023,Ind-1237,4,15,Net Banking,1500.0,225.0,1275.0
4,Eva,C005,India,Product5,250.0,270.0,NaN,5/8/2023,Ind-1238,1,0,UPI,250.0,0.0,250.0

### 🎯 Student Challenge — Calculated Column

Create a new column named `Price Difference` equal to `MRP - Sale Price` in a copy of `sales`.

**Hint:** Create a copy first. Pandas can subtract two columns directly.

Ask students to try this before showing the solution.

In [72]:
# Write your answer here.

**Teacher solution — run this only after students have tried.**

In [73]:
# Create a copy of the original sales data.
price_difference_demo = sales.copy()

# Subtract Sale Price from MRP and store the result in a new column.
price_difference_demo["Price Difference"] = (
    price_difference_demo["MRP"] - price_difference_demo["Sale Price"]
)

# Display the relevant columns.
price_difference_demo[["MRP", "Sale Price", "Price Difference"]].head(10)

     MRP  Sale Price  Price Difference
0  120.0       100.0              20.0
1  170.0       150.0              20.0
2    NaN       200.0               NaN
3  210.0         NaN               NaN
4  270.0       250.0              20.0
5  320.0       300.0              20.0
6    NaN       350.0               NaN
7  370.0         NaN               NaN
8  420.0       400.0              20.0
9    NaN       450.0               NaN

## 16. `unique()`, `nunique()`, and `value_counts()`

In [74]:
# Display all unique Payment Mode values.
print("Unique payment modes:")
print(sales["Payment Mode"].unique())

# Count how many distinct Payment Mode values exist.
print("\nNumber of unique payment modes:")
print(sales["Payment Mode"].nunique())

# Count how many times each Payment Mode occurs.
print("\nFrequency of each payment mode:")
print(sales["Payment Mode"].value_counts())

Unique payment modes:
<ArrowStringArray>
['UPI', 'Card', 'Cash', 'Net Banking']
Length: 4, dtype: str

Number of unique payment modes:
4

Frequency of each payment mode:
Payment Mode
Card           8
UPI            6
Cash           3
Net Banking    3
Name: count, dtype: int64

### 16.1 Value Counts Including Missing Values

In [75]:
# Count each Product Name and also include missing values.
product_counts = sales["Product Name"].value_counts(dropna=False)

# Display the counts.
product_counts

Product Name
NaN          4
Product14    3
Product1     2
Product2     2
Product8     2
Product4     1
Product5     1
Product7     1
Product9     1
Product11    1
Product12    1
Product13    1
Name: count, dtype: int64

## 17. `map()`, `replace()`, and `apply()`

### Quick Difference

- `map()` → usually used on a **Series**, often for one-to-one mapping.
- `replace()` → replace known values with other values.
- `apply()` → apply a custom function to a Series or along DataFrame rows/columns.

### 17.1 `map()` with a Dictionary

In [76]:
# Create a dictionary that converts payment modes into broader payment groups.
payment_group_map = {
    "UPI": "Digital",
    "Card": "Digital",
    "Net Banking": "Digital",
    "Cash": "Offline"
}

# Create a new column by mapping each Payment Mode to its group.
analysis_sales["Payment Group"] = analysis_sales["Payment Mode"].map(
    payment_group_map
)

# Display the result.
analysis_sales[["Payment Mode", "Payment Group"]].head(10)

  Payment Mode Payment Group
0          UPI       Digital
1         Card       Digital
2         Cash       Offline
3  Net Banking       Digital
4          UPI       Digital
5         Card       Digital
6          UPI       Digital
7         Card       Digital
8         Cash       Offline
9  Net Banking       Digital

### 17.2 `apply()` with a Custom Function

In [77]:
# Define a function that converts numeric ratings into simple text categories.
def rating_category(rating):
    # Return Unknown when the value is missing.
    if pd.isna(rating):
        return "Unknown"
    # Return Excellent for ratings of 4.5 or more.
    if rating >= 4.5:
        return "Excellent"
    # Return Good for ratings of 4.0 or more.
    if rating >= 4.0:
        return "Good"
    # Return Average for all remaining ratings.
    return "Average"

# Apply the function to every value in the Rating column.
analysis_sales["Rating Category"] = analysis_sales["Rating"].apply(
    rating_category
)

# Display the result.
analysis_sales[["Rating", "Rating Category"]].head(10)

   Rating Rating Category
0     4.5       Excellent
1     4.0            Good
2     3.5         Average
3     5.0       Excellent
4     NaN         Unknown
5     4.7       Excellent
6     4.1            Good
7     3.8         Average
8     NaN         Unknown
9     4.3            Good

### 17.3 Row-wise `apply(axis=1)`

In [78]:
# Define a function that reads values from one complete row.
def order_size(row):
    # Return Bulk when Quantity is 4.
    if row["Quantity"] >= 4:
        return "Bulk"
    # Return Regular for smaller quantities.
    return "Regular"

# Apply the function row by row using axis=1.
analysis_sales["Order Size"] = analysis_sales.apply(
    order_size,
    axis=1
)

# Display the result.
analysis_sales[["Quantity", "Order Size"]].head(10)

   Quantity Order Size
0         1    Regular
1         2    Regular
2         3    Regular
3         4       Bulk
4         1    Regular
5         2    Regular
6         1    Regular
7         2    Regular
8         3    Regular
9         4       Bulk

### 🎯 Student Challenge — `apply()`

Create a column named `Price Level`: return `High` when `Sale Price >= 500`, otherwise return `Low`. Missing values can also be treated as `Low` for this beginner exercise.

**Hint:** Write a function, then apply it to the `Sale Price` column.

Ask students to try this before showing the solution.

In [79]:
# Write your answer here.

**Teacher solution — run this only after students have tried.**

In [80]:
# Define a function that labels prices.
def price_level(price):
    # Return High for prices of 500 or more.
    if price >= 500:
        return "High"
    # Return Low for all other values.
    return "Low"

# Create a copy for the exercise solution.
apply_question = sales.copy()

# Apply the function to the Sale Price column.
apply_question["Price Level"] = apply_question["Sale Price"].apply(
    price_level
)

# Display the result.
apply_question[["Sale Price", "Price Level"]].head(10)

   Sale Price Price Level
0       100.0         Low
1       150.0         Low
2       200.0         Low
3         NaN         Low
4       250.0         Low
5       300.0         Low
6       350.0         Low
7         NaN         Low
8       400.0         Low
9       450.0         Low

## 18. GroupBy and Aggregation

`groupby()` follows the idea:

**Split → Apply → Combine**

Example: split rows by payment method, calculate a statistic for each group, then combine the results.

### 18.1 Group by One Column

In [81]:
# Group rows by Payment Mode and calculate the mean Sale Price.
average_price_by_payment = (
    analysis_sales
    .groupby("Payment Mode")["Sale Price"]
    .mean()
)

# Display the result.
average_price_by_payment

Payment Mode
Card           360.000000
Cash           383.333333
Net Banking    475.000000
UPI            325.000000
Name: Sale Price, dtype: float64

### 18.2 Group and Sum

In [82]:
# Group by Payment Mode and calculate total Net Sales for each group.
net_sales_by_payment = (
    analysis_sales
    .groupby("Payment Mode")["Net Sales"]
    .sum()
    .sort_values(ascending=False)
)

# Display the result.
net_sales_by_payment

Payment Mode
Net Banking    4845.0
Card           3420.0
Cash           3105.0
UPI            1950.0
Name: Net Sales, dtype: float64

### 18.3 Multiple Aggregations with `agg()`

In [83]:
# Group by Payment Mode and calculate several statistics in one operation.
payment_summary = (
    analysis_sales
    .groupby("Payment Mode")
    .agg(
        Orders=("Code", "count"),
        Average_Rating=("Rating", "mean"),
        Total_Quantity=("Quantity", "sum"),
        Total_Net_Sales=("Net Sales", "sum"),
    )
    .reset_index()
)

# Display the summary table.
payment_summary

  Payment Mode  Orders  Average_Rating  Total_Quantity  Total_Net_Sales
0         Card       5        4.275000              10           3420.0
1         Cash       3        3.700000               9           3105.0
2  Net Banking       3        4.633333              12           4845.0
3          UPI       6        4.440000               6           1950.0

### 🎯 Student Challenge — GroupBy

Find the total `Quantity` sold for each `Payment Mode`.

**Hint:** Group by `Payment Mode`, select `Quantity`, and use `sum()`.

Ask students to try this before showing the solution.

In [84]:
# Write your answer here.

**Teacher solution — run this only after students have tried.**

In [85]:
# Group rows by Payment Mode and add the Quantity values in each group.
sales.groupby("Payment Mode")["Quantity"].sum()

Payment Mode
Card           16
Cash            9
Net Banking    12
UPI             6
Name: Quantity, dtype: int64

## 19. Pivot Table and Crosstab

### 19.1 Pivot Table

In [86]:
# Create a pivot table showing average Sale Price by Payment Mode.
payment_pivot = pd.pivot_table(
    analysis_sales,
    index="Payment Mode",
    values="Sale Price",
    aggfunc="mean"
)

# Display the pivot table.
payment_pivot

              Sale Price
Payment Mode
Card          360.000000
Cash          383.333333
Net Banking   475.000000
UPI           325.000000

### 19.2 Crosstab

In [87]:
# Count how many orders belong to each combination of Payment Mode and Order Size.
payment_order_crosstab = pd.crosstab(
    analysis_sales["Payment Mode"],
    analysis_sales["Order Size"]
)

# Display the crosstab.
payment_order_crosstab

Order Size    Bulk  Regular
Payment Mode
Card             0        5
Cash             0        3
Net Banking      3        0
UPI              0        6

## 20. Concatenating DataFrames with `pd.concat()`

Use `concat()` when tables have the same or compatible structure and you want to stack them.

- `axis=0` → stack rows vertically
- `axis=1` → place columns side by side

### 20.1 Concatenate Rows

In [88]:
# Create the first small DataFrame.
class_a = pd.DataFrame(
    {
        "Name": ["Aman", "Priya"],
        "Marks": [80, 92]
    }
)

# Create the second small DataFrame.
class_b = pd.DataFrame(
    {
        "Name": ["Rohit", "Neha"],
        "Marks": [85, 88]
    }
)

# Stack the two DataFrames vertically and create a fresh continuous index.
combined_students = pd.concat(
    [class_a, class_b],
    axis=0,
    ignore_index=True
)

# Display the combined rows.
combined_students

    Name  Marks
0   Aman     80
1  Priya     92
2  Rohit     85
3   Neha     88

### 20.2 Concatenate Columns

In [89]:
# Create a DataFrame containing student names.
student_names = pd.DataFrame(
    {"Name": ["Aman", "Priya", "Rohit"]}
)

# Create a second DataFrame with marks using the same row index.
student_scores = pd.DataFrame(
    {"Marks": [80, 92, 85]}
)

# Place both DataFrames side by side.
side_by_side = pd.concat(
    [student_names, student_scores],
    axis=1
)

# Display the result.
side_by_side

    Name  Marks
0   Aman     80
1  Priya     92
2  Rohit     85

## 21. Merge Two CSV Files — Real Join Example

Now we will work with multiple files, just like a real project.

Files:

- `sales_data_class.csv` → transaction data
- `product_details.csv` → product master data
- `customer_details.csv` → customer master data

`merge()` is similar to SQL joins.

### 21.1 Load the Product Master File

In [90]:
# Read the product master CSV file.
products = pd.read_csv("product_details.csv")

# Display the first five rows.
products.head()

  Product Name     Category   Brand    Supplier  Cost Price
0     Product1  Electronics    Nova  Supplier A          88
1     Product2  Accessories   Orbit  Supplier B         106
2     Product3         Home  Vertex  Supplier C         124
3     Product4  Electronics   Prime  Supplier A         142
4     Product5       Office     Zen  Supplier B         160

### 21.2 Left Join Sales with Product Details

In [91]:
# Merge every sales row with matching product information.
sales_with_products = pd.merge(
    sales,
    products,
    on="Product Name",
    how="left"
)

# Display useful columns after the merge.
sales_with_products[
    ["Name", "Product Name", "Category", "Brand", "Sale Price"]
].head(12)

       Name Product Name     Category   Brand  Sale Price
0     Alice     Product1  Electronics    Nova       100.0
1       Bob     Product2  Accessories   Orbit       150.0
2   Charlie          NaN          NaN     NaN       200.0
3     David     Product4  Electronics   Prime         NaN
4       Eva     Product5       Office     Zen       250.0
5     Frank          NaN          NaN     NaN       300.0
6     Grace     Product7  Accessories   Orbit       350.0
7     Helen     Product8         Home  Vertex         NaN
8       Ivy     Product9  Electronics   Prime       400.0
9      Jack          NaN          NaN     NaN       450.0
10     Kara    Product11  Electronics    Nova       500.0
11      Leo    Product12  Accessories   Orbit         NaN

**Why is `left` useful here?**

We normally want to keep every transaction from the sales file even when a product lookup is missing.

### 21.3 Compare Inner, Left, Right, and Outer Joins

In [92]:
# Keep only keys that exist in both DataFrames.
inner_join = pd.merge(
    sales,
    products,
    on="Product Name",
    how="inner"
)

# Keep every row from the left sales DataFrame.
left_join = pd.merge(
    sales,
    products,
    on="Product Name",
    how="left"
)

# Keep every row from the right products DataFrame.
right_join = pd.merge(
    sales,
    products,
    on="Product Name",
    how="right"
)

# Keep every key from both DataFrames.
outer_join = pd.merge(
    sales,
    products,
    on="Product Name",
    how="outer"
)

# Compare the number of rows created by each join type.
print("Inner join rows:", len(inner_join))
print("Left join rows:", len(left_join))
print("Right join rows:", len(right_join))
print("Outer join rows:", len(outer_join))

Inner join rows: 16
Left join rows: 20
Right join rows: 20
Outer join rows: 24

### 21.4 Use `indicator=True` to See Where Rows Came From

In [93]:
# Perform an outer join and ask Pandas to show the source of each row.
join_check = pd.merge(
    sales,
    products,
    on="Product Name",
    how="outer",
    indicator=True
)

# Count rows that matched, came only from the left, or came only from the right.
join_check["_merge"].value_counts()

_merge
both          16
left_only      4
right_only     4
Name: count, dtype: int64

### 21.5 Merge Customer Details

In [94]:
# Read the customer master CSV file.
customers = pd.read_csv("customer_details.csv")

# Merge customer information into the sales-plus-products DataFrame.
full_sales = pd.merge(
    sales_with_products,
    customers[["Customer ID", "City", "State", "Segment"]],
    on="Customer ID",
    how="left"
)

# Display selected columns from the fully combined data.
full_sales[
    [
        "Customer ID",
        "Name",
        "City",
        "Segment",
        "Product Name",
        "Category",
        "Sale Price",
    ]
].head(12)

,Customer ID,Name,City,Segment,Product Name,Category,Sale Price
0,C001,Alice,Delhi,Consumer,Product1,Electronics,100.0
1,C002,Bob,Noida,Corporate,Product2,Accessories,150.0
2,C003,Charlie,Mumbai,Consumer,NaN,NaN,200.0
3,C004,David,Gurugram,Home Office,Product4,Electronics,NaN
4,C005,Eva,Jaipur,Consumer,Product5,Office,250.0
5,C006,Frank,Pune,Corporate,NaN,NaN,300.0
6,C007,Grace,Lucknow,Consumer,Product7,Accessories,350.0
7,C008,Helen,Ghaziabad,Home Office,Product8,Home,NaN
8,C009,Ivy,Bengaluru,Corporate,Product9,Electronics,400.0
9,C010,Jack,Chandigarh,Consumer,NaN,NaN,450.0
10,C011,Kara,Kolkata,Corporate,Product11,Electronics,500.0
11,C012,Leo,Ahmedabad,Consumer,Product12,Accessories,NaN

### 🎯 Student Challenge — Merge

Using `sales` and `customers`, create an **inner join** on `Customer ID`. Then display `Customer ID`, `Name`, `City`, and `Segment`.

**Hint:** Use `pd.merge(..., on='Customer ID', how='inner')`.

Ask students to try this before showing the solution.

In [95]:
# Write your answer here.

**Teacher solution — run this only after students have tried.**

In [96]:
# Merge sales and customer data using only matching Customer ID values.
customer_inner = pd.merge(
    sales,
    customers,
    on="Customer ID",
    how="inner",
    suffixes=("_sales", "_customer")
)

# Display selected columns.
customer_inner[
    ["Customer ID", "Name_sales", "City", "Segment"]
].head(10)

  Customer ID Name_sales        City      Segment
0        C001      Alice       Delhi     Consumer
1        C002        Bob       Noida    Corporate
2        C003    Charlie      Mumbai     Consumer
3        C004      David    Gurugram  Home Office
4        C005        Eva      Jaipur     Consumer
5        C006      Frank        Pune    Corporate
6        C007      Grace     Lucknow     Consumer
7        C008      Helen   Ghaziabad  Home Office
8        C009        Ivy   Bengaluru    Corporate
9        C010       Jack  Chandigarh     Consumer

## 22. `join()` Using Indexes

`join()` is commonly used when the matching key has been placed in the index.

For beginners, remember:

- `merge()` → very flexible, usually joins using columns.
- `join()` → especially convenient when joining by index.

In [97]:
# Put Customer ID in the index of the sales DataFrame.
sales_indexed = sales.set_index("Customer ID")

# Put Customer ID in the index of the customer master DataFrame.
customers_indexed = customers.set_index("Customer ID")

# Join selected customer columns into the sales data by matching indexes.
joined_by_index = sales_indexed.join(
    customers_indexed[["City", "State", "Segment"]],
    how="left"
)

# Convert Customer ID from the index back into a normal column.
joined_by_index = joined_by_index.reset_index()

# Display selected columns.
joined_by_index[
    ["Customer ID", "Name", "City", "State", "Segment"]
].head(10)

  Customer ID     Name        City          State      Segment
0        C001    Alice       Delhi          Delhi     Consumer
1        C002      Bob       Noida  Uttar Pradesh    Corporate
2        C003  Charlie      Mumbai    Maharashtra     Consumer
3        C004    David    Gurugram        Haryana  Home Office
4        C005      Eva      Jaipur      Rajasthan     Consumer
5        C006    Frank        Pune    Maharashtra    Corporate
6        C007    Grace     Lucknow  Uttar Pradesh     Consumer
7        C008    Helen   Ghaziabad  Uttar Pradesh  Home Office
8        C009      Ivy   Bengaluru      Karnataka    Corporate
9        C010     Jack  Chandigarh     Chandigarh     Consumer

## 23. Analysis After Merge

### 23.1 Total Sales by Category

In [98]:
# Start from the fully merged table and remove exact duplicate rows.
merged_analysis = full_sales.drop_duplicates().copy()

# Fill missing Sale Price values with the median.
merged_analysis["Sale Price"] = merged_analysis["Sale Price"].fillna(
    merged_analysis["Sale Price"].median()
)

# Calculate Gross Sales.
merged_analysis["Gross Sales"] = (
    merged_analysis["Sale Price"] * merged_analysis["Quantity"]
)

# Calculate Net Sales after discount.
merged_analysis["Net Sales"] = (
    merged_analysis["Gross Sales"]
    * (1 - merged_analysis["Discount %"] / 100)
)

# Group by Category and calculate total Net Sales.
category_sales = (
    merged_analysis
    .groupby("Category", dropna=False)["Net Sales"]
    .sum()
    .sort_values(ascending=False)
)

# Display the result.
category_sales

Category
Electronics    6235.0
NaN            3290.0
Home           2197.5
Accessories    1347.5
Office          250.0
Name: Net Sales, dtype: float64

### 23.2 Total Sales by City

In [99]:
# Group by City and calculate total Net Sales.
city_sales = (
    merged_analysis
    .groupby("City", dropna=False)["Net Sales"]
    .sum()
    .sort_values(ascending=False)
)

# Display the first ten cities.
city_sales.head(10)

City
Hyderabad     3180.0
Chandigarh    1530.0
Indore        1485.0
Gurugram      1275.0
Bengaluru     1080.0
Ahmedabad      712.5
Ghaziabad      712.5
Chennai        650.0
Pune           570.0
Mumbai         540.0
Name: Net Sales, dtype: float64

## 24. Correlation — A Gentle Introduction

Correlation measures how strongly numeric columns move together.

- close to `1` → strong positive relationship
- close to `-1` → strong negative relationship
- close to `0` → little linear relationship

Correlation does **not** automatically mean one variable causes another.

In [100]:
# Select numeric columns that are useful for a simple correlation example.
numeric_columns = merged_analysis[
    ["Sale Price", "MRP", "Rating", "Quantity", "Discount %", "Net Sales"]
]

# Calculate the correlation matrix.
correlation_matrix = numeric_columns.corr()

# Display the matrix.
correlation_matrix

            Sale Price       MRP    Rating  Quantity  Discount %  Net Sales
Sale Price    1.000000  0.929453  0.171609  0.296794    0.296794   0.711486
MRP           0.929453  1.000000  0.041237  0.146539    0.146539   0.576615
Rating        0.171609  0.041237  1.000000  0.002131    0.002131   0.146360
Quantity      0.296794  0.146539  0.002131  1.000000    1.000000   0.843571
Discount %    0.296794  0.146539  0.002131  1.000000    1.000000   0.843571
Net Sales     0.711486  0.576615  0.146360  0.843571    0.843571   1.000000

## 25. Save Data Back to CSV

In [101]:
# Choose only a few useful columns for the exported classroom result.
export_data = merged_analysis[
    [
        "Customer ID",
        "Name",
        "City",
        "Product Name",
        "Category",
        "Sale Price",
        "Quantity",
        "Discount %",
        "Net Sales",
    ]
].copy()

# Save the DataFrame as a new CSV file without writing the Pandas index.
export_data.to_csv(
    "class_output_sales.csv",
    index=False
)

# Confirm the file name for students.
print("Saved: class_output_sales.csv")

Saved: class_output_sales.csv

## 26. Final Student Practice — Do Not Show Solutions Immediately

### Question 1
Display the first 8 rows of the sales data.

### Question 2
Show only `Name`, `Sale Price`, and `Rating`.

### Question 3
Find all rows where `Sale Price` is greater than 400.

### Question 4
Find rows where `Rating >= 4.0` and `Quantity >= 3`.

### Question 5
Count missing values in every column.

### Question 6
Display all exact duplicate rows.

### Question 7
Remove duplicate rows without changing the original `sales` DataFrame.

### Question 8
Create a new column named `Total Before Discount` equal to `Sale Price * Quantity`.

### Question 9
Find the total Quantity sold for each Payment Mode.

### Question 10
Merge sales with `product_details.csv` using a left join.

### Question 11
Find total Net Sales for each product Category after the merge.

### Question 12
Export your final result to a CSV file.

In [102]:
# Use this cell for Question 1.

In [103]:
# Use this cell for Question 2.

In [104]:
# Use this cell for Question 3.

In [105]:
# Use this cell for Question 4.

In [106]:
# Use this cell for Question 5.

In [107]:
# Use this cell for Question 6.

In [108]:
# Use this cell for Question 7.

In [109]:
# Use this cell for Question 8.

In [110]:
# Use this cell for Question 9.

In [111]:
# Use this cell for Question 10.

In [112]:
# Use this cell for Question 11.

In [113]:
# Use this cell for Question 12.

## 27. Teacher Cheat Sheet

| Task | Common Pandas Code |
|---|---|
| Read CSV | `pd.read_csv()` |
| First rows | `df.head()` |
| Last rows | `df.tail()` |
| Rows and columns | `df.shape` |
| Column names | `df.columns` |
| Data types | `df.dtypes` |
| Summary | `df.info()` / `df.describe()` |
| Missing values | `df.isna().sum()` |
| Remove missing | `df.dropna()` |
| Fill missing | `df.fillna()` |
| Find duplicates | `df.duplicated()` |
| Remove duplicates | `df.drop_duplicates()` |
| Select by labels | `df.loc[]` |
| Select by position | `df.iloc[]` |
| One cell by label | `df.at[]` |
| One cell by position | `df.iat[]` |
| Sort | `df.sort_values()` |
| Count categories | `df.value_counts()` |
| Group data | `df.groupby()` |
| Map values | `Series.map()` |
| Apply function | `Series.apply()` / `DataFrame.apply()` |
| Stack tables | `pd.concat()` |
| Join tables | `pd.merge()` |
| Join by index | `df.join()` |
| Save CSV | `df.to_csv()` |

### Recommended teaching pace

Do not try to teach every section in one class.

A good sequence is:

- **Class 1:** Series + DataFrame + reading CSV + inspection
- **Class 2:** selection + `loc` + `iloc` + filtering + sorting
- **Class 3:** missing values + dates + duplicates + text cleaning
- **Class 4:** updating + new columns + `map` + `apply`
- **Class 5:** GroupBy + pivot + concat
- **Class 6:** merge + join + complete mini-analysis